name: Deploy to prod server
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22.18.0

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ~/.npm  # npm 全局缓存
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline

      - name: build
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192" && npm run build

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          path: ./dist/
          remote_path: /opt/html/ams-mng
          remote_host: 39.108.73.143
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_port: 22
